####Chr1~22_beforeLD.txt _> SNP_subset_AllFrePass_1~22.txt

#SNP_Pass_All_Fre_Check: SNPs passed all population Frequency check
#SNP_subset_AllFrePass: subset of SNP_Pass_All_Fre_Check

#SNP_LE: SNPs from SNP_subset_AllFrePass that are in linkage equilibrium
#ALL_SNP_r2: all pairwise r2 between SNP_LE
#r2_SNP: r2 for a specific SNP that is currently under check
#snp_chri: all snps who passed manual LD check
#badSnps: snps row numbers who failed R script LD check


#SNP_LE_full: SNPs who passed LD check, with full details
#SNP_LE: rs only version of SNP_LE_full
####

#choose a subset of qualified SNPs from each chromosome and test their linkage equalibrium

# generate a random subset as the candidate to be check LD at LDmatrix
# high r2 SNPs were removed BY HAND (=~=)
#r2 matrix was generated by http://analysistools.nci.nih.gov/LDlink/
snp <- data.frame(matrix(ncol = 1, nrow = 0))
for (i in 1:22){
  
  SNP_Pass_All_Fre_Check <- read.csv(paste0("/Users/jianyiren/Desktop/ProjectReconnect/5-LD/chr",i,"_beforeLD.txt"), sep="")
  names(SNP_Pass_All_Fre_Check)[1] <- "rs."
  SNP_subset_AllFrePass <- SNP_Pass_All_Fre_Check[seq(1, length(SNP_Pass_All_Fre_Check$rs.), 3),]
  write.csv(SNP_subset_AllFrePass,paste0("/Users/jianyiren/Desktop/ProjectReconnect/5-LD/SNP_subset_AllFrePass_",i,".txt"),row.names = FALSE,quote = FALSE)
}

#  check LD of snps by r script
r2_Threashold <- 0.017
SNP_LE <- vector()
ALL_SNP_r2 <-vector()

for (i in 1:22){
  path <- paste0("/Users/jianyiren/Desktop/ProjectReconnect/5-LD/Chr",toString(i),"_r2.txt")
  snp_chri <-  read.csv(path, sep="")
  badSnps = vector()
  for (j in 1:dim(snp_chri)[1]){
    
    r2_SNP <- (snp_chri[j,])
    r2_SNP <- sort(r2_SNP, decreasing = TRUE)
    if (r2_SNP[3] > r2_Threashold) {
      badSnps = c(badSnps,j)
    } else {
      ALL_SNP_r2 <-c(ALL_SNP_r2,snp_chri[j,][2:(dim(snp_chri)[2]+1-j)])
      }
  }
  #print(length(badSnps) )
  if (length(badSnps) != 0) {
      snp_chri <- snp_chri[-badSnps,] 
    } else {
      print("0")
    }
    
  SNP_LE <- rbind(SNP_LE,data.frame(snp_chri$RS_number))
}
ALL_SNP_r2 <-as.numeric(ALL_SNP_r2)
ALL_SNP_r2 <-subset(ALL_SNP_r2,ALL_SNP_r2<1)
print(mean(ALL_SNP_r2))
print(sd(ALL_SNP_r2))
print(max(ALL_SNP_r2))

#Save results
#rs. only version    
names(SNP_LE) <-"rs."
write.csv(SNP_LE, "/Users/jianyiren/Desktop/ProjectReconnect/SNP_LE.txt",quote = FALSE, row.names = FALSE)

#detailed information version 
snp <- data.frame(matrix(ncol = 6, nrow = 0))
for (i in 1:22){
  read_name<- paste0("chr",toString(i),"_full")
  new_snp <-read.csv(paste0("/Users/jianyiren/Desktop/ProjectReconnect/Preliminary_result/",read_name,".txt"), sep=",")
  snp <- rbind(snp,new_snp)
}

SNP_LE_full <- subset(snp, (snp$rs. %in% SNP_LE$rs.))#
write.csv(SNP_LE_full, "/Users/jianyiren/Desktop/ProjectReconnect/SNP_LE_full.txt",quote = FALSE, row.names = FALSE)


    

  
  